### ISSUE TITLE
"_one" missing in the .setup_assistant file

### ISSUE THREAD

**Issue by smaassen** [NiryoRobotics/niryo_one_ros#1]
the move_it setup assistent file is missing "_one" in the paths for urdf and srdf, which makes it impossible to edit the move_it configuration, say for other grippers

**Comment by renarded** [comment]
Hi,

Thanks for the info. The issue has been fixed [here](https://github.com/NiryoRobotics/niryo_one_ros/commit/56bdb2cba2a25e881f8599ef5a6e944e152eafc7).
