### ISSUE TITLE
lack of developper documentation

### ISSUE THREAD

**Issue by smaassen** [NiryoRobotics/niryo_one_ros#11]
Hi, 

I understand that there are higher priorities than keeping up with the documentation for developing in Ros, so I uploaded some of the code I used to get started to a github repo. 

https://github.com/smaassen/niryo_one_tester

It is a basic example for c++ but could be extended with further examples. You are welcome to refer to it as long as you do not have your own examples.

Best

**Comment by renarded** [comment]
Hi,

Thank you for this contribution ! I've added a link to your repository on the main README, under "Developer Documentation" section.
