### ISSUE TITLE
Asseble

### ISSUE THREAD

**Issue by hapav** [NiryoRobotics/niryo_one_ros#24]
Hello,
im slowly trying to assemble my robot and now i have problem cause i cant find sizes of alluminium tubes. Can you help me please?

Thank you

**Comment by renarded** [comment]
Hi hapav,

Could you send a Technical Support request [from our website](https://niryo.com/contact/) ? (don't forget to fill in your order number).

This is the fastest and most convenient way to contact us for any issue related to your order. Hope you understand! Thanks.
