### ISSUE TITLE
extend robot commander to execture precomputed trajectory

### ISSUE THREAD

**Issue by smaassen** [NiryoRobotics/niryo_one_ros#3]
I think i found out a possibility to extend the current framework to directly use the robot commander to execute precomputed trajectories (say from a moveIt node running on another system)

Would it be possible to get access rights in order to do a pull request, so you can make a code review and maybe merge it into the master branch?

 Best Steve

**Comment by renarded** [comment]
Hi Steve,

That's great !

On our side we also put this feature on our TO-DO list for the next few weeks. This would be nice to have a look at your code.

To make a pull request you don't need access rights, please follow [this guide](https://help.github.com/articles/creating-a-pull-request-from-a-fork/). You'll have to fork the repo and then create a pull request from your fork.
