### ISSUE TITLE
Can not change Modbus port from 5020 to 502

### ISSUE THREAD

**Issue by Thuunderbear** [NiryoRobotics/niryo_one_ros#58]
Hello,
This bug occur on ned one.
In "~/catkin_ws/src/niryo_robot_modbus/launch/modbus_server.launch" when changing :

> \<arg name="server_port" default="**5020**"/>

as recommended to

> \<arg name="server_port" default="**502**"/>

nothing happen after restarting ( I check the port using nmap and nothing has change).

After some research I reach the niryo_robot_modbus package folder by using :
> roscd niryo_robot_modbus

it send me to "~/catkin_ws/install/release/ned/share/niryo_robot_modbus/launch" folder and when I try to change the same file in this folder after this commands :

>  rosdep fix-permissions

> roslauch niryo_robot_modbus modbus_server.launch

Thes modbus TCP port is closed and I have an error 

> ModbusServer.init : TCP server unable to start : [Errno 13] Permission denied

(sudo seems to doesn't work )

Could you help me ?

Thanks

**Comment by ValentinPitre** [comment]
Hi, I'm not sure if you are in the right repository :) 
Maybe this one [https://github.com/NiryoRobotics/ned_ros](url)  would be better
