### ISSUE TITLE
wrong angle wrappping in niryo one studio

### ISSUE THREAD

**Issue by smaassen** [NiryoRobotics/niryo_one_ros#6]
Hi, 

I do not know where to address this, since there is no github for niryo one studio so I'll just post it here. 
It appears that the angle wrappings are not working for the two last axes (5 & 6). When you move the joint from the middle (0) to one extrimity it goes from 0 to PI/2 to 0 again. 

I think it should go to PI or -PI respectively.

**Comment by renarded** [comment]
Hi @smaassen,

We have made a lot of changes in the Niryo One Studio software recently. Could you try again with the new version (available [here](https://niryo.com/download/), documentation on how to upgrade [here](https://niryo.com/docs/niryo-one/update-your-robot/)) and tell me if you still have the same error ?
