### ISSUE TITLE
No inertial info for each link

### ISSUE THREAD

**Issue by UK-Roy** [NiryoRobotics/niryo_one_ros#63]
Hi,
I'm Utsha.

I want to use niryo_one robot in gym environment. For that reason I want a proper urdf file consist of collision, visual and inertial information. But the provided urdf file does not contain the inertial information. 

How can I get those inertial information for each link?
 Thanks in advanced

**Comment by aubino** [comment]
Hi @UK-Roy. Since the description is made by stl and collada files, the resulting urdf files does not require inertia values to work. I suggest you put the stl files into a cad software (solidworks, FreeCAD or even blender) to find inertial values of each element of the design.
